#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x102C2C17498D6B9E (i.tkomiya@gmail.com)
#
Name     : pypi-sphinxcontrib_jsmath
Version  : 1.0.1
Release  : 33
URL      : https://files.pythonhosted.org/packages/b2/e8/9ed3830aeed71f17c026a07a5097edcf44b692850ef215b161b8ad875729/sphinxcontrib-jsmath-1.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/b2/e8/9ed3830aeed71f17c026a07a5097edcf44b692850ef215b161b8ad875729/sphinxcontrib-jsmath-1.0.1.tar.gz
Source1  : https://files.pythonhosted.org/packages/b2/e8/9ed3830aeed71f17c026a07a5097edcf44b692850ef215b161b8ad875729/sphinxcontrib-jsmath-1.0.1.tar.gz.asc
Summary  : A sphinx extension which renders display math in HTML via JavaScript
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-sphinxcontrib_jsmath-license = %{version}-%{release}
Requires: pypi-sphinxcontrib_jsmath-python = %{version}-%{release}
Requires: pypi-sphinxcontrib_jsmath-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
sphinxcontrib-jsmath is a sphinx extension which renders display math in HTML
        via JavaScript.

%package license
Summary: license components for the pypi-sphinxcontrib_jsmath package.
Group: Default

%description license
license components for the pypi-sphinxcontrib_jsmath package.


%package python
Summary: python components for the pypi-sphinxcontrib_jsmath package.
Group: Default
Requires: pypi-sphinxcontrib_jsmath-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinxcontrib_jsmath package.


%package python3
Summary: python3 components for the pypi-sphinxcontrib_jsmath package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_jsmath)

%description python3
python3 components for the pypi-sphinxcontrib_jsmath package.


%prep
%setup -q -n sphinxcontrib-jsmath-1.0.1
cd %{_builddir}/sphinxcontrib-jsmath-1.0.1
pushd ..
cp -a sphinxcontrib-jsmath-1.0.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656409388
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_jsmath
cp %{_builddir}/sphinxcontrib-jsmath-1.0.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_jsmath/95a954a1c89e9eb976234b1909028a4bdb8e9e28
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinxcontrib_jsmath/95a954a1c89e9eb976234b1909028a4bdb8e9e28

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
